[template]
description = "Development environment with nickel and mask"
welcomeText = '''
# Welcome to your new Nix development environment!

This template provides:
- Nickel configuration language
- Mask task runner
- Treefmt code formatter
- Automatic environment loading with direnv

Get started:
1. Run `direnv allow` (if you have direnv installed)
2. Or run `nix develop` to enter the development shell
3. Run `mask --help` to see available tasks
4. Run `treefmt` to format your code

Happy coding! 🚀
'''